### ISSUE TITLE
Sign-in error stuck at the bottom of the screen

### ISSUE THREAD

**Issue by meredithrouse** [NewSpring/Holtzman#1902] opened 2017-05-25 20:58 UTC
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to login screen.
2. Type in a correct email.
3. Type in the wrong password.

I am using iOS.

### Buggy Behavior

Describe the thing that happens that is the issue.

### Expected Behavior

Describe what should actually happen.

### Screenshots

![image_uploaded_from_ios_720-3](https://cloud.githubusercontent.com/assets/19376946/26470339/51715fc0-416b-11e7-93cb-0382d15874d9.jpg)

**Comment by jbaxleyiii** [comment] 2017-05-25 23:59
caused by #1910. Closing in favor of that issue

**Closed by jbaxleyiii** 2017-05-25 23:59 UTC
